### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'undefined' is invalid.

### ISSUE THREAD

**Issue by trusktr** [sergei-startsev/karma-stacktrace#10]
After updating from karma 4.1.0 to 6.3.4, I get this error:

```
Electron 12.0.2 (Node 14.16.0) ERROR
  An error was thrown in afterAll
  Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'undefined' is invalid. thrown
```

The code that tries to execute `importScripts` is from `karma-stacktrace` here:

https://github.com/sergei-startsev/karma-stacktrace/blob/a20cf40a1cbe1a288f4c2203eafb3594b0ab18e4/lib/stacktrace.js#L185-L195

where `stacktracejsURL` is `undefined`.

Any idea why updating `karma` breaks `karma-stacktrace` or causes this error to show up?

**Comment by sergei-startsev** [comment]
@trusktr Could you please check if the issue is specific for Karma 6+? Is it reproduced for Karma 5?

I guess `stacktrace.min.js` wasn't added to the scripts list during the framework initialization:
https://github.com/sergei-startsev/karma-stacktrace/blob/a20cf40a1cbe1a288f4c2203eafb3594b0ab18e4/lib/index.js#L17
Though I don't see anything about that in Karma 6 [breaking changes](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#breaking-changes).

**Comment by trusktr** [comment]
To be honest, I was flying with such haste to update my project that I completely don't remember what I ended up doing to get around the issue. I'll re-open if it comes back and if I can reproduce it.
